---
- name: Install Docker and Docker Compose
  hosts: vm2
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

- name: Deploy Application
  hosts: vm2
  become: true
  tasks:
    - name: Clone repository
      git:
        repo: https://github.com/TheMatrix2/lab08.git
        dest: /home/vagrant/app/

    - name: Start Docker Compose
      command: docker-compose up -d
      args:
        chdir: /home/vagrant/app/